name: VeciDoInventare
version: 1.0
main: veci.MainVeci
api-version: 1.18

commands:
  _boty:
  _brneni:
  _helma:
  _kalhoty:
  _vybava:
  _lukSipy:
  _trojzubec:
  _mec:
  _motyka:
  _sekera:
  _stit:
  _krumpac:
  _krovky:
  _jablko:
  _mrkevNaPrutu:
  _vlnaBloku:
    description: sip leti, bloky pod nim vyskakuji, udela to vlnu
    usage: /<prikaz> [rychlostSipu1-2] [leti true/false] [pasazer true/false] [maxBloky<200]
  _zmenaMaterialu:
    description: zmeni jeden material na druhy
    usage: /<prikaz> [vychoziMaterial] [cilovyMaterial]